name: tama2_app
description: "基于Flutter的Tama2移动端应用，仿抖音风格"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 国际化支持
  flutter_localizations:
    sdk: flutter
  flutter_i18n: ^0.36.3
  
  # 网络请求
  dio: ^5.3.2
  
  # 状态管理
  provider: ^6.1.1
  
  # 路由管理
  go_router: ^12.1.1
  
  # 视频播放
  video_player: ^2.8.1
  video_player_web: ^2.1.2
  video_view: ^1.1.4
  
  # 图片缓存
  cached_network_image: ^3.3.0
  
  # 图片选择和裁剪
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  
  # 本地存储
  shared_preferences: ^2.2.2
  
  # UI组件
  pull_to_refresh: ^2.0.0
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.1
  
  # 工具类
  json_annotation: ^4.8.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/flutter_i18n/
  
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
